### ISSUE TITLE
Question: Submit to Homebrew

### ISSUE THREAD

**Issue by marcobiedermann** [lukechilds/gifgen#1]
How about making this library available via Homebrew?
See [Formula-Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md) for more instructions.

**Comment by lukechilds** [comment]
That's creepy, I was literally halfway through adding this to Homebrew and your notification came through.

Should be done in a couple of mins 👍

**Comment by marcobiedermann** [comment]
@lukechilds Awesome! 🎉

**Comment by lukechilds** [comment]
Sorted!

``` shell
brew tap lukechilds/tap
brew install gifgen
```

I'll update the readme when I get in from work 😄
