### ISSUE TITLE
Funny Twitter Thread about this repo!

### ISSUE THREAD

**Issue by ahmadawais** [lukechilds/gifgen#5]
I shared the docs on Twitter and it ignited quite a conversation. Morten and Ansel have some good points there — I figured I'd let you know :)

Take a look → https://twitter.com/MrAhmadAwais/status/883544471996157952

**Comment by lukechilds** [comment]
Heheh, thanks for letting me know, seems like it struck a nerve.

I don't have a Windows box to test on and back when I released this there was no Windows Subsystem for Linux so installation would have been a bit of a pain. Happy to accept a PR.

**Comment by ahmadawais** [comment]
I don't Windows either. 💯

**Comment by williamd1k0** [comment]
I just tested in Windows 10 using *Git Bash*, the basic command worked very well :D 

![image](https://user-images.githubusercontent.com/10428035/28082818-eb3f52bc-6649-11e7-895f-6e8e3a6f2cee.png)
