### ISSUE TITLE
how to update 1.2 ？

### ISSUE THREAD

**Issue by dong108** [lukechilds/gifgen#9]
It was 1.1.2 after I installed it

**Comment by lukechilds** [comment]
I'm assuming you're installing from homebrew?

The tap was outdated. I've just updated it (https://github.com/lukechilds/homebrew-tap/commit/1ee9e0ed296502997ee7552f74c7dff36afcf9d9) so if you re-install you should be on the latest version.

**Comment by dong108** [comment]
Thank you very much
